config:
  target: 'http://localhost:4003'
  phases:
    - duration: 60
      arrivalRate: 250
  defaults:
    headers:
      Authorization: 'Bearer your-access-token'
scenarios:
  - flow:
      - get:
          url: "/users"
